version: 2

prelude: &prelude
  docker:
  - image: bodak/rust-python-alpine:2022-09-23
  working_directory: ~/hmrb

setup_code_climate: &setup_code_climate
  run:
    name: setup code climate
    command: |
      apk add --no-cache curl
      curl -L -o cc-test-reporter https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64
      chmod +x cc-test-reporter
      ./cc-test-reporter before-build
upload_code_climate: &upload_code_climate
  run:
    name: upload coverage results
    command: |
      apk add --no-cache git
      ./cc-test-reporter after-build -t coverage.py --exit-code $?

not_master: &not_master
  filters:
    branches:
      ignore:
      - master

release_tags: &release_tags
  filters:
    branches:
      ignore:
      - /^.*$/
    tags:
      only:
      - /^(\d|\.)+$/

release_candidate_tags: &release_candidate_tags
  filters:
    branches:
      ignore:
      - /^.*$/
    tags:
      only:
      - /^(\d|\.)+rc\d$/

workflows:
  version: 2
  build-and-test:
    jobs:
    - lint:
        <<: *not_master
    - test:
        <<: *not_master
    - release-candidate:
        <<: *release_candidate_tags
    - release:
        context: babylon
        <<: *release_tags

jobs:
  test:
    <<: *prelude
    steps:
    - checkout
    - run: |
        pip3 install cython
        pip3 install nox
        make tests
  lint:
    <<: *prelude
    steps:
    - checkout
    - run: |
        pip3 install nox
        make lint
        make type
        make safety
  release-candidate:
    <<: *prelude
    steps:
      - checkout
      - run: |
          pip3 install nox
          make publish
  release:
    <<: *prelude
    steps:
      - checkout
      - run: |
          pip3 install nox
          make publish-confirm
